module.exports = {
  "platform": "元力QQ",
  "author": "鍏紬鍙�:绉戞妧闀块潚",
  "version": "0.1.0",
  "srcUrl": "http://music.haitangw.net/cqapi/qq.js",
  "cacheControl": "no-cache",
  "hints": {
    "importMusicSheet": [
      "QQ音乐APP：自建歌单-分享-分享到微信好友/QQ好友；然后点开并复制链接，直接粘贴即可",
      "H5：复制URL并粘贴，或者直接输入纯数字歌单ID即可",
      "瀵煎叆鏃堕棿鍜屾瓕鍗曞ぇ灏忔湁鍏筹紝璇疯€愬績绛夊緟"
    ]
  },
  "primaryKey": [
    "id",
    "songmid"
  ],
  "supportedSearchType": [
    "music",
    "album",
    "sheet",
    "artist",
    "lyric"
  ],
  "search": "async (keyword, page = 1, type = 'music') => {\n    console.log(`调用search方法: ${keyword}, 页码: ${page}, 类型: ${type}`);\n    \n    // 根据搜索类型返回不同结果\n    switch (type) {\n        case 'music':\n            return {\n                isEnd: true,\n                data: [\n                    {\n                        id: '0039MnYb0qxYhV',\n                        songmid: '0039MnYb0qxYhV',\n                        name: '晴天',\n                        artist: '周杰伦',\n                        album: '叶惠美',\n                        cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                        duration: 246\n                    }\n                ]\n            };\n        \n        case 'album':\n            return {\n                isEnd: true,\n                data: [\n                    {\n                        id: '004MhY8f18mWXH',\n                        albumMID: '004MhY8f18mWXH',\n                        title: '叶惠美',\n                        artist: '周杰伦',\n                        artwork: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                        date: '2003-07-31'\n                    }\n                ]\n            };\n        \n        case 'artist':\n            return {\n                isEnd: true,\n                data: [\n                    {\n                        id: '6452',\n                        singerID: '6452',\n                        singerMID: '002J4UUk29y8BY',\n                        name: '周杰伦',\n                        avatar: 'https://y.qq.com/music/photo_new/T001R300x300M000002J4UUk29y8BY.jpg'\n                    }\n                ]\n            };\n        \n        case 'sheet':\n            return {\n                isEnd: true,\n                data: [\n                    {\n                        id: '8295059087',\n                        title: '周杰伦经典',\n                        artist: '用户123',\n                        cover: 'https://y.qq.com/music/photo_new/T004R300x300M000003p3Dgs3tVZ6f.jpg',\n                        description: '周杰伦的经典歌曲集合',\n                        playCount: 123456\n                    }\n                ]\n            };\n        \n        case 'lyric':\n            return {\n                isEnd: true,\n                data: []\n            };\n        \n        default:\n            return {\n                isEnd: true,\n                data: []\n            };\n    }\n}",
  "getMediaSource": "async (params, quality = 'standard') => {\n    console.log(`调用getMediaSource方法: songmid=${params.songmid}, quality=${quality}`);\n    \n    // 返回媒体源信息\n    return {\n        url: `https://example.com/music/${params.songmid}.mp3`,\n        type: 'audio/mpeg',\n        quality: quality,\n        size: '1024000'\n    };\n}",
  "getLyric": "async (params) => {\n    console.log(`调用getLyric方法: songmid=${params.songmid}`);\n    \n    // 返回歌词信息\n    return {\n        rawLrc: '[00:00.00]晴天 - 周杰伦\\n[00:05.00]作词：周杰伦\\n[00:10.00]作曲：周杰伦\\n[00:15.00]故事的小黄花 从出生那年就飘着',\n        translation: '[00:15.00]The little yellow flower of the story has been floating since the year I was born'\n    };\n}",
  "getAlbumInfo": "async (params) => {\n    console.log(`调用getAlbumInfo方法: albumMID=${params.albumMID}`);\n    \n    // 返回专辑信息\n    return {\n        albumItem: {\n            id: '004MhY8f18mWXH',\n            albumMID: '004MhY8f18mWXH',\n            title: '叶惠美',\n            artist: '周杰伦',\n            artwork: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n            date: '2003-07-31',\n            description: '周杰伦的第四张专辑'\n        },\n        musicList: [\n            {\n                id: '0039MnYb0qxYhV',\n                songmid: '0039MnYb0qxYhV',\n                name: '晴天',\n                artist: '周杰伦',\n                album: '叶惠美',\n                cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                duration: 246\n            },\n            {\n                id: '001J4UUk29y8BY',\n                songmid: '001J4UUk29y8BY',\n                name: '三年二班',\n                artist: '周杰伦',\n                album: '叶惠美',\n                cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                duration: 260\n            }\n        ],\n        isEnd: true\n    };\n}",
  "getArtistWorks": "async (artist, page = 1, type = 'music') => {\n    console.log(`调用getArtistWorks方法: artistID=${artist.id}, 页码: ${page}, 类型: ${type}`);\n    \n    // 根据作品类型返回不同结果\n    if (type === 'music') {\n        return {\n            isEnd: true,\n            data: [\n                {\n                    id: '0039MnYb0qxYhV',\n                    songmid: '0039MnYb0qxYhV',\n                    name: '晴天',\n                    artist: '周杰伦',\n                    album: '叶惠美',\n                    cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                    duration: 246\n                },\n                {\n                    id: '001J4UUk29y8BY',\n                    songmid: '001J4UUk29y8BY',\n                    name: '三年二班',\n                    artist: '周杰伦',\n                    album: '叶惠美',\n                    cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                    duration: 260\n                }\n            ]\n        };\n    }\n    \n    return {\n        isEnd: true,\n        data: []\n    };\n}",
  "importMusicSheet": "async (url) => {\n    console.log(`调用importMusicSheet方法: url=${url}`);\n    \n    // 返回导入的歌曲列表\n    return [\n        {\n            id: '0039MnYb0qxYhV',\n            songmid: '0039MnYb0qxYhV',\n            name: '晴天',\n            artist: '周杰伦',\n            album: '叶惠美',\n            cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n            duration: 246\n        },\n        {\n            id: '001J4UUk29y8BY',\n            songmid: '001J4UUk29y8BY',\n            name: '三年二班',\n            artist: '周杰伦',\n            album: '叶惠美',\n            cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n            duration: 260\n        }\n    ];\n}",
  "getTopLists": "async () => {\n    console.log('调用getTopLists方法');\n    \n    // 返回排行榜列表\n    return [\n        {\n            title: '热门榜单',\n            data: [\n                {\n                    id: '4',\n                    description: 'QQ音乐官方榜',\n                    title: '热歌榜',\n                    period: '每日更新',\n                    coverImg: 'https://y.qq.com/music/photo_new/T003R300x300M000004Z0QlU19C3eX.jpg'\n                },\n                {\n                    id: '26',\n                    description: 'QQ音乐官方榜',\n                    title: '新歌榜',\n                    period: '每日更新',\n                    coverImg: 'https://y.qq.com/music/photo_new/T003R300x300M000004Z0QlU19C3eX.jpg'\n                },\n                {\n                    id: '5',\n                    description: 'QQ音乐官方榜',\n                    title: '飙升榜',\n                    period: '每日更新',\n                    coverImg: 'https://y.qq.com/music/photo_new/T003R300x300M000004Z0QlU19C3eX.jpg'\n                }\n            ]\n        },\n        {\n            title: '流行金曲',\n            data: [\n                {\n                    id: '11',\n                    description: 'QQ音乐官方榜',\n                    title: '流行指数榜',\n                    period: '每周更新',\n                    coverImg: 'https://y.qq.com/music/photo_new/T003R300x300M000004Z0QlU19C3eX.jpg'\n                },\n                {\n                    id: '12',\n                    description: 'QQ音乐官方榜',\n                    title: '欧美热歌榜',\n                    period: '每周更新',\n                    coverImg: 'https://y.qq.com/music/photo_new/T003R300x300M000004Z0QlU19C3eX.jpg'\n                }\n            ]\n        }\n    ];\n}",
  "getTopListDetail": "async (toplist, page = 1) => {\n    console.log(`调用getTopListDetail方法: toplistID=${toplist.id}, 页码: ${page}`);\n    \n    // 返回排行榜详情\n    return {\n        isEnd: true,\n        topListItem: {\n            id: '4',\n            description: 'QQ音乐官方榜',\n            title: '热歌榜',\n            period: '每日更新',\n            coverImg: 'https://y.qq.com/music/photo_new/T003R300x300M000004Z0QlU19C3eX.jpg'\n        },\n        musicList: [\n            {\n                id: '0039MnYb0qxYhV',\n                songmid: '0039MnYb0qxYhV',\n                name: '晴天',\n                artist: '周杰伦',\n                album: '叶惠美',\n                cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                duration: 246\n            },\n            {\n                id: '001J4UUk29y8BY',\n                songmid: '001J4UUk29y8BY',\n                name: '三年二班',\n                artist: '周杰伦',\n                album: '叶惠美',\n                cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                duration: 260\n            }\n        ]\n    };\n}",
  "getRecommendSheetTags": "async () => {\n    console.log('调用getRecommendSheetTags方法');\n    \n    // 返回推荐歌单标签\n    return {\n        pinned: [\n            {\n                id: '1',\n                title: '热门推荐'\n            }\n        ],\n        data: [\n            {\n                title: '风格',\n                data: [\n                    {\n                        id: '10000000',\n                        title: '流行'\n                    },\n                    {\n                        id: '20000000',\n                        title: '摇滚'\n                    },\n                    {\n                        id: '30000000',\n                        title: '民谣'\n                    }\n                ]\n            },\n            {\n                title: '场景',\n                data: [\n                    {\n                        id: '40000000',\n                        title: '驾车'\n                    },\n                    {\n                        id: '50000000',\n                        title: '工作'\n                    },\n                    {\n                        id: '60000000',\n                        title: '学习'\n                    }\n                ]\n            }\n        ]\n    };\n}",
  "getRecommendSheetsByTag": "async (tag, page = 1) => {\n    console.log(`调用getRecommendSheetsByTag方法: tagID=${tag.id}, 页码: ${page}`);\n    \n    // 返回按标签推荐的歌单\n    return {\n        isEnd: true,\n        data: [\n            {\n                id: '8295059087',\n                title: '周杰伦经典',\n                artist: '用户123',\n                cover: 'https://y.qq.com/music/photo_new/T004R300x300M000003p3Dgs3tVZ6f.jpg',\n                description: '周杰伦的经典歌曲集合',\n                playCount: 123456\n            },\n            {\n                id: '8295059088',\n                title: '华语流行精选',\n                artist: '用户456',\n                cover: 'https://y.qq.com/music/photo_new/T004R300x300M000003p3Dgs3tVZ6f.jpg',\n                description: '华语流行歌曲精选',\n                playCount: 789012\n            }\n        ]\n    };\n}",
  "getMusicSheetInfo": "async (sheet, page = 1) => {\n    console.log(`调用getMusicSheetInfo方法: sheetID=${sheet.id}, 页码: ${page}`);\n    \n    // 返回歌单信息\n    return {\n        isEnd: true,\n        sheetItem: {\n            id: '8295059087',\n            title: '周杰伦经典',\n            artist: '用户123',\n            cover: 'https://y.qq.com/music/photo_new/T004R300x300M000003p3Dgs3tVZ6f.jpg',\n            description: '周杰伦的经典歌曲集合',\n            playCount: 123456,\n            createTime: '2023-01-01'\n        },\n        musicList: [\n            {\n                id: '0039MnYb0qxYhV',\n                songmid: '0039MnYb0qxYhV',\n                name: '晴天',\n                artist: '周杰伦',\n                album: '叶惠美',\n                cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                duration: 246\n            },\n            {\n                id: '001J4UUk29y8BY',\n                songmid: '001J4UUk29y8BY',\n                name: '三年二班',\n                artist: '周杰伦',\n                album: '叶惠美',\n                cover: 'https://y.qq.com/music/photo_new/T002R300x300M000003p3Dgs3tVZ6f.jpg',\n                duration: 260\n            }\n        ]\n    };\n}"
}